version: '3'

services:
  rick-monitor:
    build: .
    container_name: rick-monitor
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
